import MumbaiIndians from './assets/team logo/mi.png';
import ChennaiSuperKings from './assets/team logo/csk.png';
import KolkataKnightRiders from './assets/team logo/kkr.png';
import DelhiCapitals from './assets/team logo/dc.png';
import SunrisersHyderabad from './assets/team logo/srh.png';
import GujaratTitans from './assets/team logo/gt.png';
import RajasthanRoyals from './assets/team logo/rrs.png';
import RoyalChallengersBengaluru from './assets/team logo/rcb.png';
import LucknowSuperGiants from './assets/team logo/lsg.png';
import PunjabKings from './assets/team logo/pk.png';

const teamsData = [
  {
    id: 1,
    name: 'Mumbai Indians',
    country: 'India',
    logo: MumbaiIndians,
    description: 'Mumbai Indians is a franchise cricket team representing Mumbai, Maharashtra in the IPL.',
    championshipsWon: 5,
    captain: 'Rohit Sharma',
    coach: 'Mahela Jayawardene',
    founded: '24 January 2008',
    stadium: 'Wankhede Stadium',
    owner: 'Indiawin Sports Pvt. Ltd',
  },
  {
    id: 2,
    name: 'Kolkata Knight Riders',
    country: 'India',
    logo: KolkataKnightRiders,
    description: 'KKR stands for Kolkata Knight Riders, a cricket team that plays in the Indian Premier League (IPL).',
    championshipsWon: 2,
    captain: 'Shreyas Iyer',
    coach: 'Chandrakant Pandit',
    founded: '24 January 2008',
    stadium: 'Eden Gardens',
    owner: 'Knight Riders Sports Private Ltd',
  },
  {
    id: 3,
    name: 'Chennai Super Kings',
    country: 'India',
    logo: ChennaiSuperKings,
    description: 'Chennai Super Kings is a franchise cricket team based in Chennai, Tamil Nadu, India.',
    championshipsWon: 5,
    captain: 'MS Dhoni',
    coach: 'Stephen Fleming',
    founded: '24 January 2008',
    stadium: 'M. A. Chidambaram Stadium',
    owner: 'Chennai Super Kings Cricket Ltd.',
  },
  {
    id: 4,
    name: 'Delhi Capitals',
    country: 'India',
    logo: DelhiCapitals,
    description: 'Delhi Capitals, formerly Delhi Daredevils, are a professional franchise cricket team based in Delhi that plays in the Indian Premier League.',
    championshipsWon: 0,
    captain: 'Ricky Ponting',
    coach: 'Rishabh Pant',
    founded: '2008',
    stadium: '',
    owner: '',
  },
  {
    id: 5,
    name: 'Sunrisers Hyderabad',
    country: 'India',
    logo: SunrisersHyderabad,
    description: 'Sunrisers Hyderabad are a professional franchise cricket team based in Hyderabad, Telangana, India, that plays in the Indian Premier League.',
    championshipsWon: 1,
    captain: 'Aiden Markram',
    coach: 'Brian Lara',
    founded: '',
    stadium: '',
    owner: '',
  },
  {
    id: 6,
    name: 'Gujarat Titans',
    country: 'India',
    logo: GujaratTitans,
    description: 'Gujarat Titans is a professional franchise cricket team based in Ahmedabad, Gujarat, that plays in the Indian Premier League.',
    championshipsWon: 1,
    captain: 'Hardik Pandya',
    coach: 'Ashish Nehra',
    founded: '',
    stadium: '',
    owner: '',
  },
  {
    id: 7,
    name: 'Rajasthan Royals',
    country: 'India',
    logo: RajasthanRoyals,
    description: 'Rajasthan Royals are a professional franchise cricket team based in Jaipur, Rajasthan, that competes in the Indian Premier League.',
    championshipsWon: 1,
    captain: 'Sanju Samson',
    coach: 'Kumar Sangakkara',
    founded: '',
    stadium: '',
    owner: '',
  },
  {
    id: 8,
    name: 'Royal Challengers Bengaluru',
    country: 'India',
    logo: RoyalChallengersBengaluru,
    description: 'Royal Challengers Bengaluru is a professional franchise cricket team based in Bengaluru, Karnataka, that competes in the Indian Premier League.',
    championshipsWon: 0,
    captain: 'Faf du Plessis',
    coach: 'Sanjay Bangar',
    founded: '',
    stadium: '',
    owner: '',
  },
  {
    id: 9,
    name: 'Lucknow Super Giants',
    country: 'India',
    logo: LucknowSuperGiants,
    description: 'Lucknow Super Giants is a professional franchise cricket team based in Lucknow, Uttar Pradesh that competes in the Indian Premier League.',
    championshipsWon: 0,
    captain: 'KL Rahul',
    coach: 'Andy Flower',
    founded: '',
    stadium: '',
    owner: '',
  },
  {
    id: 10,
    name: 'Punjab Kings',
    country: 'India',
    logo: PunjabKings,
    description: 'Punjab Kings is a professional franchise cricket team based in Mohali, Punjab, that competes in the Indian Premier League.',
    championshipsWon: 0,
    captain: 'Shikhar Dhawan',
    coach: 'Trevor Bayliss',
    founded: '',
    stadium: '',
    owner: '',
  },
];

export default teamsData;